### ISSUE TITLE
Extra html inside active <li> item

### ISSUE THREAD

**Issue by mileszim** [codeplant/simple-navigation#132]
Is it possible to add an extra bit of html (like a span tag) in whatever <li> item is active?

**Comment by phansch** [comment]
Unfortunately `content` doesn't support html, only text. I want to add font-awesome icons to the beginning of some list elements, but it seems it is not so easy.

**Comment by simonc** [comment]
@phansch Using `name_generator` is the easiest way to do it (doing what your trying to do is the reason I added `item` as a second argument to the block.

If abusing `name_generator` makes you uncomfortable, the idea is that you can create your own navigation renderer to suit your needs :-)
