### ISSUE TITLE
Auto-generate IDs?

### ISSUE THREAD

**Issue by jmuheim** [codeplant/simple-navigation#177]
I find it annoying that I have to specify an ID for each and every menu item manually, as I don't even need them most of the time.

Is there a way to dismiss them? When leaving the first parameter of `#item` `nil`, it still adds an `id` attribute, simply with no value.

**Comment by simonc** [comment]
Hi @jmuheim,

Actually it's not an id, it's an identifying key that _may_ be used to generate ids. There is an option to disable the ids generation if you want to:

```
# Item keys are normally added to list items as id.
# This setting turns that off
# navigation.autogenerate_item_ids = false
```
