### ISSUE TITLE
Passing a block with HTML to an item

### ISSUE THREAD

**Issue by jmuheim** [codeplant/simple-navigation#178]
I want to have a megadropdown in one of my navigations like this:

![image](https://cloud.githubusercontent.com/assets/1814983/6842592/5f3837b4-d39a-11e4-95fe-0e665cc31932.png)

I'm unsure about how to place the megadropdown code in the view, though. I tried it like this:

```ruby
- navigation.item :navigation_sign_in, t('.sign_in') do |sub_navigation|
  - sub_navigation.item :navigation_sign_in_panel do
    .yamm-content
      .row = render 'devise/sessions/form', resource: User.new, display: :small
```

This results in the following error:

    wrong number of arguments (1 for 2..4)

Is there a way to give a block with HTML to the `item` so it is rendered as item content?

**Comment by andi** [comment]
@jmuheim simple-navigation currently does not support mixing navigation configuration DSL and HTML/haml code

**Comment by jmuheim** [comment]
This is very sad and the main reason I switched to https://github.com/jejacks0n/navigasmic.
