### ISSUE TITLE
v4.0.1 not setting link class

### ISSUE THREAD

**Issue by joost** [codeplant/simple-navigation#179]
primary.item :my_primary_item, 'Home', home_path, :class => 'li_class', :link => {:class => 'link_class', :title => 'my_title'}

This does not seem to work for me in the latest version.

**Comment by andi** [comment]
Hi @joost, you are right. From v4 you have to specify attributes on li and a tag as follows:

    primary.item :my_primary_item, 'Home', home_path, :html => {:class => 'li_class'}, :link_html => {:class => 'link_class', :title => 'my_title'}

Will update the docs accordingly...

**Comment by joost** [comment]
Ok thanks!

BTW. What's new about v4? Or is it 'just' refactoring?

**Comment by joost** [comment]
Another thing I saw was that all my links now seem to be 'active' (get a .active css class).

**Comment by andi** [comment]
Just updated the wiki and added a little upgrade hint
https://github.com/codeplant/simple-navigation/wiki#upgrade-hint-for-v400

Will check about active class

**Comment by andi** [comment]
Can you give an example on the active class? How does your config file look like? I just checked on the demo project https://github.com/codeplant/simple-navigation-demo and everything works as expected.

**Comment by andi** [comment]
@joost any updates on your active class issue?

**Comment by joost** [comment]
I have to look into it.. nvmd for now :) I will close it.
