### ISSUE TITLE
how to change the "selected" class name?

### ISSUE THREAD

**Issue by rubytastic** [codeplant/simple-navigation#181]
I could not find anything in the documentation regarding on how to change the 'selected' classname.
My goal is change it from 'selcted' to 'active' the documentation only lists it can be changed in the config file but no mention how.

Could anyone please add a documentation entry on how to do this? kind regards

**Comment by simonc** [comment]
Hi @rubytastic,

It's not in the readme but when you use the generator it's present in the comments of the generated file
https://github.com/codeplant/simple-navigation/blob/master/generators/navigation_config/templates/config/navigation.rb#L9-L10

But you're right, it should be present in the doc as well. Could you add it in the wiki in a way that make sense to someone looking for this the same way you did? :)

**Comment by andi** [comment]
@rubytastic maybe you could add an entry in the FAQs? https://github.com/codeplant/simple-navigation/wiki/FAQ. Thanks
