### ISSUE TITLE
Items without URLs

### ISSUE THREAD

**Issue by existent-co-uk** [codeplant/simple-navigation#187]
I believe this used to work, at some point --- see issue #77. Trying to configure an item without a URL, such as
```ruby
primary.item :dog, 'Dog'
```

results in a "no implicit conversion of nil into String" error. Explicitly using `nil`, or even `"#"`, results in the same error.

The configuration documentation in the Wiki claims that this is a supported use case.

**Comment by simonc** [comment]
Hi @existent-co-uk.

It is indeed supported and this error is a bug. I'll investigate and get back to you ;)

**Comment by existent-co-uk** [comment]
## Update

This is likely _not_ a bug in `simple-navigation` after all. Just attempted to recreate in a clean Rails project, and could not do so. Sorry for the noise.

**Comment by simonc** [comment]
Good news :) Thank you for your feedback! Hope you find find where it's coming from.
