### ISSUE TITLE
Render breadcrumbs for post requests

### ISSUE THREAD

**Issue by blelump** [codeplant/simple-navigation#193]
Hi!

I wonder how you deal with rendering breadcrumbs nav and an invalid form? In particular, for some reason validation returned with form errors and the form have been re–rendered from within POST request. 

I'm seeing breadcrumbs nav uses [`selected?`](https://github.com/codeplant/simple-navigation/blob/master/lib/simple_navigation/renderer/breadcrumbs.rb#L27) method, which in case of Rails, internally uses `current_page?`from `UrlHelper`. It implies, however, that `current_page?` will always return false, because of [this](https://github.com/rails/rails/blob/v4.2.5/actionview/lib/action_view/helpers/url_helper.rb#L533) statement and hence breadcrumbs nav will not be rendered at all. 

Am I missing something here?

**Comment by andi** [comment]
Are you referring to the fact that URL changes after failing validation? (i.e. it will become the same URL as the index action)...

If yes, you might check out this quite old thread #49 and scroll to the very bottom for a working solution...

**Comment by blelump** [comment]
@andi ,

thanks for your response. The uri path doesn't change, it stays as it was while rendering the form first time. My point here is that `current_page?` always returns false if the request is not GET or HEAD.

**Comment by andi** [comment]
if you rely on autohighlight (without configuring anything regarding highlighting), yes you are right, it will not work for POST or PUT request, for those scenarios you have to use highlights_on

**Comment by joelw** [comment]
I haven't examined if there are any other implications of doing so in our application, but setting `navigation.highlight_on_subpath = true` seems to fix URL matching for POST/PUT.
