### ISSUE TITLE
rendering on a static page?

### ISSUE THREAD

**Issue by dsusco** [codeplant/simple-navigation#198]
I'd like to render my nav on my error pages. They're not dynamic, and are pre-compiled alongside my app's assets. Any thoughts, examples or tips for doing something like this?

**Comment by andi** [comment]
Usually on completely "standalone" error pages I would consider just writing the nav in plain HTML. I would currently not know if there are any obstacles in the asset precompilation process when using simple-navigation. If you really need it, please investigate.
