### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by n-rodriguez** [codeplant/simple-navigation#202]
Please :)

**Comment by andi** [comment]
will do :-)

**Comment by andi** [comment]
Sorry for my dumb question, but what issue did you PR exactly solve?

**Comment by andi** [comment]
it was #184. So was it only test related?

**Comment by n-rodriguez** [comment]
> So was it only test related?

It seems to be. I'd like to get rid of this : https://github.com/jbox-web/simple_navigation_bootstrap/blob/master/Gemfile#L8

**Comment by andi** [comment]
4.0.4 released

**Comment by n-rodriguez** [comment]
Thank you!
