### ISSUE TITLE
Generate data to a A tag.

### ISSUE THREAD

**Issue by jairbj** [codeplant/simple-navigation#205]
Hi friends, I didn't find a way to generate data to a generated A tag.

Like this:
```
<li class="nav-item start ">
    <a href="dashboard_2.html" class="nav-link ">
        <i class="icon-bulb"></i>
        <span class="title">Dashboard 2</span>
        <span class="badge badge-success">1</span>
    </a>
</li>

```
How to generate theese I/SPAN tags inside the A tag?

**Comment by andi** [comment]
If your HTML needs to look different you have two options:
- use the name_generator in the config file
- write a custom renderer (you have all the flexibility here)

See comments in #201 and #203
