### ISSUE TITLE
Non-deterministic behaviour when running in multiple threads

### ISSUE THREAD

**Issue by mkarklins** [codeplant/simple-navigation#206]
I have a rails app running in multiple threads. When the workload is high enough, the rendered navigation produces strange results - as if it had skipped few navigation elements.

I created a gist with reproduction steps [here](https://gist.github.com/mkarklins/7842bec597c72ac24ca15bf581a10694).

An example result is this:

> Books, Music
<...>
Books, Music
Books, Music
Books, Music, records, record_1, record_2
Books, Music
Books, Music
Books, Music
Books, Music
Books, Music

Using simple-navigation 4.0.5

Could someone provide an insight on where lies the problem?

**Comment by andi** [comment]
Thanks for the gist... simple-navigation has probably never been tested in a multithreaded high workload environment and it has never been an issue so far. Due to time constraints I would appreciate if you could investigate and contribute your findings. Thanks!

**Comment by mkarklins** [comment]
The way I got around the problem was to simply synchronise the execution across threads: 

```
# initializer
class SimpleNavigationPatch
  def self.mutex
    @mutex ||= Mutex.new
  end
end

# layout.html
SimpleNavigationPatch.mutex.synchronize { render_navigation }
```

This is not pretty and has performance penalties, but renders the navigation correctly. Since this is working now and doesn't seem like such a major problem, I'll probably won't have the motivation to dig deeper.  

Guess we can close this now.

**Comment by andi** [comment]
Ok, thanks for your feedback.
