### ISSUE TITLE
Support &block on link_to and content_tag

### ISSUE THREAD

**Issue by SirRawlins** [codeplant/simple-navigation#208]
I'm working with a custom renderer today and calling on link_to and content_tag, however, I notice that the adapted versions in the rails adapter don't appear to support passing a block for rendering more complex content with the content_tag and/or link_to.

http://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to

Are there any specific reasons why we don't want this supported? Or am I safe to wrap up a PR to add this functionality in?

**Comment by andi** [comment]
No, there is no specific reason and hence PR is very welcome :-)
